#!/bin/sh

if [ $# -eq 0 ]; then
case "$(git -C /run/src pull --ff-only)" in
*Already\ up\ to\ date*) echo "nothing to do" && exit 0 ;;
*       ) echo updating ;;
esac
else
  git -C /run/src pull --ff-only
fi

/usr/bin/hugo -s /run/src -d /run/dst -D --cleanDestinationDir
